hmrc/manage-external-guidance-frontend

app/controllers/AccessibilityStatementController.scala
app/views/accessibility_statement.scala.html
app/views/components/FooterLinks.scala
app/views/main_layout.scala.html
conf/app.routes
conf/messages.en
it/pages/AccessibilityStatementControllerISpec.scala
test/controllers/AccessibilityStatementControllerSpec.scala
test/controllers/apis/ScratchControllerSpec.scala
test/mocks/MockAuditConector.scala
test/mocks/MockAuditService.scala
test/services/AuditServiceSpec.scala

Accessibility page and footer links - and some formatting changes after running scalafmtAll

Eg 418 footers

---

app/connectors/ReviewConnector.scala
app/connectors/httpParsers/ReviewHttpParser.scala
app/models/ApprovalProcessReview.scala
app/models/PageReview.scala
app/models/PageReviewStatus.scala
app/models/errors/Error.scala
test/connectors/ReviewConnectorSpec.scala
test/connectors/httpParsers/ReviewHttpParserSpec.scala
test/mocks/MockHttpClient.scala
test/models/ReviewData.scala

New Connector for 2i review - just created one status class with NotStarted and Complete - thinking that the display value will be handled via message config on page

EG-472 - New connector for retrieving 2i process review page list with status

---

app/connectors/ReviewConnector.scala
app/connectors/httpParsers/ReviewHttpParser.scala
app/models/ApprovalProcessStatusChange.scala
test/connectors/ReviewConnectorSpec.scala
test/connectors/httpParsers/ReviewHttpParserSpec.scala
test/views/ApprovalsListSpec.scala
test/views/TwoEyeReviewSpec.scala

and minor formatting updates after scala format

EG-481 StatusChange Connector 

---

app/controllers/actions/AuthenticatedIdentifierAction.scala
app/controllers/actions/TwoEyeReviewerAuthenticatedIdentifierAction.scala
app/models/requests/IdentifierRequest.scala
conf/messages.en
it/pages/AdminControllerISpec.scala
it/stubs/AuthStub.scala
test/base/ControllerBaseSpec.scala
test/controllers/actions/AuthenticatedIdentifierActionSpec.scala
test/controllers/actions/FakeIdentifierAction.scala
test/controllers/actions/FakeTwoEyeReviewerIdentifierAction.scala
test/controllers/actions/TwoEyeReviewerAuthenticatedIdentifierActionSpec.scala

EG-572 Add user name to identifier request

---

app/controllers/actions/FactCheckerAuthenticatedIdentifierAction.scala
test/controllers/actions/FactCheckerAuthenticatedIdentifierActionSpec.scala
test/controllers/actions/FakeFactCheckerIdentifierAction.scala

Simple copy of existing 2i reviewer action and tests

EG-586 FactChecker Authentication Action

---

app/views/fact_check_content_review.scala.html
app/views/main_layout.scala.html
app/views/twoeye_content_review.scala.html
conf/messages.en

This pull request should not be merged until the associated test updates have been merged.

EG-615 Update content

---

app/connectors/ReviewConnector.scala
app/connectors/httpParsers/ApprovalHttpParser.scala
app/connectors/httpParsers/HttpParser.scala
app/connectors/httpParsers/ReviewHttpParser.scala
app/controllers/FactCheckConfirmController.scala
app/controllers/FactCheckPageReviewController.scala
app/controllers/TwoEyePageReviewController.scala
app/controllers/TwoEyeReviewResultController.scala
app/models/errors/Error.scala
app/services/ReviewService.scala
app/views/fact_check_complete.scala.html
app/views/fact_check_confirm_error.scala.html
app/views/fact_check_content_review.scala.html
app/views/main_layout.scala.html
app/views/twoeye_confirm_error.scala.html
conf/messages.en
it/pages/FactCheckConfirmControllerISpec.scala
it/pages/TwoEyeReviewerResultControllerISpec.scala
it/stubs/ExternalGuidanceStub.scala
test/connectors/httpParsers/ApprovalHttpParserSpec.scala
test/connectors/httpParsers/HttpParserSpec.scala
test/connectors/httpParsers/ReviewHttpParserSpec.scala
test/controllers/FactCheckConfirmControllerSpec.scala
test/controllers/FactCheckControllerSpec.scala
test/controllers/TwoEyeReviewResultControllerSpec.scala
test/mocks/MockReviewService.scala
test/views/FactCheckConfirmErrorViewSpec.scala
test/views/TwoEyeConfirmErrorViewSpec.scala
test/views/ViewSpecBase.scala

must be merged after EG-607 on external-guidance

EG-606 - Confirm all pages reviewed/Checked

---

project/AppDependencies.scala
project/build.properties
project/plugins.sbt
test/connectors/httpParsers/ApprovalHttpParserSpec.scala
test/connectors/httpParsers/HttpParserSpec.scala
test/connectors/httpParsers/ReviewHttpParserSpec.scala
test/connectors/httpParsers/ScratchHttpParserSpec.scala
test/services/AuditServiceSpec.scala

I've updated the dependencies based on the PRA.  New versions have been introduced since the PRA earlier this week, and will look into those once we have gone to what were the latest versions as of Monday

Updating dependencies and fixing issues due to upgrade

---

app/controllers/FactCheckConfirmController.scala
app/forms/TwoEyeReviewResultFormProvider.scala
app/models/ApprovalStatus.scala
app/models/ReviewType.scala
app/views/approval_summary_list.scala.html
app/views/twoeye_review_result.scala.html
conf/messages.en
it/pages/AdminControllerISpec.scala
it/pages/TwoEyeReviewerResultControllerISpec.scala
test/connectors/ReviewConnectorSpec.scala
test/connectors/httpParsers/ApprovalHttpParserSpec.scala
test/controllers/FactCheckConfirmControllerSpec.scala
test/controllers/TwoEyeReviewResultControllerSpec.scala
test/forms/TwoEyeReviewResultFormProviderSpec.scala
test/forms/mappings/ConstraintsSpec.scala
test/models/ApprovalStatusSpec.scala
test/services/ReviewServiceSpec.scala
test/views/ApprovalsListSpec.scala
test/views/TwoEyeReviewResultViewSpec.scala

Adding "In Progress" status to summary list and retrieving the review type to enable easier filtering

EG-758 partial review status

---

conf/application.conf

Same change will haveto be done to viewer if all good

Tighten CSP

---

app/models/PageReview.scala
app/views/fact_check_content_review.scala.html
app/views/twoeye_content_review.scala.html
conf/messages.en
test/models/ReviewData.scala
test/views/FactCheckReviewSpec.scala
test/views/TwoEyeReviewSpec.scala

Accept page result from external guidance and show appropriate status if page passed or failed

Update Page review Status - merge after EG-807

---

conf/messages.en
project/AppDependencies.scala

updating dependency version and changing wording to (opens in a new window or tab) after accessibility issue raised

Accessibility Fix

---

app/views/error_template.scala.html
app/views/fact_check_complete.scala.html
app/views/fact_check_confirm_error.scala.html
app/views/fact_check_content_review.scala.html
app/views/fact_check_page_review.scala.html
app/views/main_layout.scala.html
app/views/twoeye_confirm_error.scala.html
app/views/twoeye_content_review.scala.html
app/views/twoeye_page_review.scala.html
app/views/twoeye_review_result.scala.html
app/views/unauthorized_review_error_template.scala.html
test/views/FactCheckPageReviewViewSpec.scala
test/views/FactCheckReviewSpec.scala
test/views/TwoEyePageReviewViewSpec.scala
test/views/TwoEyeReviewResultViewSpec.scala
test/views/TwoEyeReviewSpec.scala
test/views/UnauthorizedReviewErrorViewSpec.scala

Issue EG-827 completed as parent task EG-820.

EG-820 Changing position of the back link

---

app/connectors/httpParsers/HttpParser.scala
app/controllers/TwoEyeReviewResultController.scala
app/models/errors/Error.scala
app/views/twoeye_complete_error.scala.html
conf/app.routes
conf/messages.en
test/connectors/httpParsers/HttpParserSpec.scala
test/connectors/httpParsers/ReviewHttpParserSpec.scala
test/controllers/FactCheckPageReviewControllerSpec.scala
test/controllers/TwoEyePageReviewControllerSpec.scala
test/controllers/TwoEyeReviewResultControllerSpec.scala
test/forms/mappings/MappingsSpec.scala
test/views/TwoEyeCompleteErrorViewSpec.scala

Must be run with associated branch on external-guidance

EG-989 changes for handling duplicate process code

---

app/assets/javascripts/gtm.js
app/config/AppConfig.scala
app/views/main_layout.scala.html
conf/application.conf
project/AppDependencies.scala
test/mocks/MockAppConfig.scala

Reverts hmrc/manage-external-guidance-frontend#135

Revert "EG-1027 Implement tracking consent mechanism"

---

app/connectors/TimescalesConnector.scala
app/connectors/httpParsers/TimescalesHttpParser.scala
app/controllers/apis/TimescalesController.scala
test/controllers/apis/TimescalesControllerSpec.scala

timescale updates for Ocelot testing purposes on staging

DL-6197g, added logging and CORS update

---

project/AppDependencies.scala

DL-9505 update play frontend hmrc to latest

---

app/views/main_layout.scala.html
conf/application.conf
project/plugins.sbt

DL-11534 CSP Config Update

---

conf/application.conf

Not used as removing DATASTREAM dependency from EG_ALL profile

DL-12512 remove auditing locally

---

project/AppDependencies.scala

New crown logo
Remove non required dependency
Tidy

DL-13043 bump up play frontend hmrc version to include new crown logo

---

build.sbt
project/AppDependencies.scala
project/plugins.sbt

DL-14995 Dependency Updates
